# Generated by Django 3.0.7 on 2020-09-04 01:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entri',
            new_name='Post',
        ),
    ]
