# Generated by Django 3.0.7 on 2020-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200904_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entri',
            name='author',
            field=models.IntegerField(),
        ),
    ]
