# Generated by Django 3.0.7 on 2020-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200904_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entri',
            name='author',
        ),
        migrations.AddField(
            model_name='entri',
            name='username',
            field=models.CharField(default='adi3d', max_length=100),
            preserve_default=False,
        ),
    ]
